#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// This structure matches the one in icg_pipeline.c
typedef struct tac_instr {
    char *instr;
    struct tac_instr *next;
} tac_instr;

// Get the TAC list generated by the previous phase
extern tac_instr *get_tac_list();

// ---------------------------------------------------------
// Optimization Phase
// ---------------------------------------------------------
void optimize_tac() {
    printf("\n=== Code Optimization Pass ===\n");
    
    tac_instr *curr = get_tac_list();
    tac_instr *prev = NULL; 
    int opt_count = 0;

    // Loop through all instructions
    while (curr != NULL) {
        char *inst = curr->instr;
        int instruction_removed = 0;
        
        // 1. Extended Algebraic Simplification (+ 0, - 0)
        if (strstr(inst, " + 0") != NULL || strstr(inst, " - 0") != NULL) {
            char result[50], var1[50];
            if (sscanf(inst, "%s = %s + 0", result, var1) == 2 || 
                sscanf(inst, "%s = %s - 0", result, var1) == 2) {
                char new_inst[100];
                sprintf(new_inst, "%s = %s", result, var1);
                printf("[Opt] Algebraic Simplification: %s  ->  %s\n", inst, new_inst);
                free(curr->instr);
                curr->instr = strdup(new_inst);
                inst = curr->instr;
                opt_count++;
            }
        }
        
        // 1b. Extended Algebraic Simplification (* 1, / 1)
        if (strstr(inst, " * 1") != NULL || strstr(inst, " / 1") != NULL) {
            char result[50], var1[50];
            if (sscanf(inst, "%s = %s * 1", result, var1) == 2 || 
                sscanf(inst, "%s = %s / 1", result, var1) == 2) {
                char new_inst[100];
                sprintf(new_inst, "%s = %s", result, var1);
                printf("[Opt] Algebraic Simplification: %s  ->  %s\n", inst, new_inst);
                free(curr->instr);
                curr->instr = strdup(new_inst);
                inst = curr->instr;
                opt_count++;
            }
        }

        // 2. Simple Strength Reduction (* 2 -> +)
        if (strstr(inst, " * 2") != NULL) {
            char result[50], var1[50];
            if (sscanf(inst, "%s = %s * 2", result, var1) == 2) {
                char new_inst[100];
                sprintf(new_inst, "%s = %s + %s", result, var1, var1);
                printf("[Opt] Strength Reduction: %s  ->  %s\n", inst, new_inst);
                free(curr->instr);
                curr->instr = strdup(new_inst);
                inst = curr->instr;
                opt_count++;
            }
        }

        // 3. Constant Folding (e.g., t1 = 5 + 3 -> t1 = 8)
        char res[50], arg1[50], op[10], arg2[50];
        if (sscanf(inst, "%s = %s %s %s", res, arg1, op, arg2) == 4) {
            // Very simple check to see if both arguments start with a digit
            if (arg1[0] >= '0' && arg1[0] <= '9' && arg2[0] >= '0' && arg2[0] <= '9') {
                int val1 = atoi(arg1);
                int val2 = atoi(arg2);
                int folded_val = 0;
                int can_fold = 1;
                
                if (strcmp(op, "+") == 0) folded_val = val1 + val2;
                else if (strcmp(op, "-") == 0) folded_val = val1 - val2;
                else if (strcmp(op, "*") == 0) folded_val = val1 * val2;
                else if (strcmp(op, "/") == 0 && val2 != 0) folded_val = val1 / val2;
                else can_fold = 0;
                
                if (can_fold) {
                    char new_inst[100];
                    sprintf(new_inst, "%s = %d", res, folded_val);
                    printf("[Opt] Constant Folding: %s  ->  %s\n", inst, new_inst);
                    free(curr->instr);
                    curr->instr = strdup(new_inst);
                    inst = curr->instr;
                    opt_count++;
                }
            }
        }
        
        // 4. Naive Dead Code Elimination (e.g., x = x)
        if (sscanf(inst, "%s = %s", res, arg1) == 2 && strcmp(res, arg1) == 0 && strstr(inst, "+") == NULL && strstr(inst, "-") == NULL && strstr(inst, "*") == NULL && strstr(inst, "/") == NULL) {
             printf("[Opt] Dead Code Eliminated (Useless Assignment): %s\n", inst);
             instruction_removed = 1;
             opt_count++;
             
             // Remove the node safely
             if (prev != NULL) {
                 prev->next = curr->next;
             }
        }
        
        // Move to next instruction
        if (!instruction_removed) {
            prev = curr;
        } else {
            // Need to free curr if we are actually fully managing memory, but for safety in this loop we just bypass it
        }
        curr = curr->next;
    }

    if (opt_count == 0) {
        printf("No optimizations could be applied.\n");
    } else {
        printf("Applied %d optimization(s) successfully.\n", opt_count);
    }
}

// ---------------------------------------------------------
// Target Code Generation Phase (Pseudo Assembly)
// ---------------------------------------------------------
void generate_target_code() {
    printf("\n=== Final Target Assembly Code ===\n");
    
    tac_instr *curr = get_tac_list();

    while (curr != NULL) {
        char inst[100];
        strcpy(inst, curr->instr);
        
        // Let's print the original TAC instruction as a comment for clarity
        printf("\n; %s\n", inst);
        
        // Variables to hold extracted text
        char result[50], arg1[50], op[10], arg2[50];
        char label_name[50], cond[50];

        // 1. Check if it is a Label (e.g., "L1:")
        if (strchr(inst, ':') != NULL) {
            printf("%s\n", inst);
        }
        
        // 2. Check for "if cond goto L1"
        else if (sscanf(inst, "if %s goto %s", cond, label_name) == 2) {
            printf("LOAD R1, %s\n", cond);
            printf("CMP R1, 0\n");
            printf("JNE %s\n", label_name);
        }
        
        // 3. Check for "goto L1"
        else if (sscanf(inst, "goto %s", label_name) == 1) {
            printf("JMP %s\n", label_name);
        }
        
        // 4. Check for "return x"
        else if (sscanf(inst, "return %s", arg1) == 1) {
            printf("LOAD R1, %s\n", arg1);
            printf("RET R1\n");
        }
        
        // 5. Binary Operations "t1 = x + y"
        else if (sscanf(inst, "%s = %s %s %s", result, arg1, op, arg2) == 4) {
            // Load operands into registers R1 and R2
            printf("LOAD R1, %s\n", arg1);
            printf("LOAD R2, %s\n", arg2);
            
            // Perform the operation and store in R3
            if (strcmp(op, "+") == 0) {
                printf("ADD R3, R1, R2\n");
            } 
            else if (strcmp(op, "-") == 0) {
                printf("SUB R3, R1, R2\n");
            } 
            else if (strcmp(op, "*") == 0) {
                printf("MUL R3, R1, R2\n");
            } 
            else if (strcmp(op, "/") == 0) {
                printf("DIV R3, R1, R2\n");
            } 
            else {
                // For logic operations (==, <, >) or bitwise
                printf("OP R3, R1, R2    // generic operation for '%s'\n", op);
            }
            
            // Store result back
            printf("STORE %s, R3\n", result);
        }
        
        // 6. Simple Assignment "x = y"
        // This is safe because we already checked for 4 arguments above!
        else if (sscanf(inst, "%s = %s", result, arg1) == 2) {
            
            // If argument starts with -, it's a unary negative (e.g. t1 = -x)
            if (arg1[0] == '-') {
                printf("LOAD R1, %s\n", arg1 + 1); // skip the negative sign
                printf("NEG R1\n");
                printf("STORE %s, R1\n", result);
            }
            else {
                // Just a normal assignment
                printf("LOAD R1, %s\n", arg1);
                printf("STORE %s, R1\n", result);
            }
        }
        
        // 7. Unknown Format
        else {
            printf("; Unhandled Instruction Structure\n");
        }
        
        curr = curr->next;
    }
    printf("==================================\n\n");
}
