#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h> // for isdigit()

// This structure matches the one in icg_pipeline.c
typedef struct tac_instr {
    char *instr;
    struct tac_instr *next;
} tac_instr;

// Get the TAC list generated by the previous phase
extern tac_instr *get_tac_list();

// ---------------------------------------------------------
// Optimization Phase
// ---------------------------------------------------------
void optimize_tac() {
    printf("\n=== Code Optimization Pass ===\n");
    
    tac_instr *curr = get_tac_list();
    tac_instr *prev = NULL; 
    int opt_count = 0;

    // Loop through all instructions
    while (curr != NULL) {
        char *inst = curr->instr;
        char res[50], arg1[50], op[10], arg2[50];
        int removed = 0;

        // Try to break the string into 4 parts: "Result = Arg1 Operator Arg2"
        int parts = sscanf(inst, "%s = %s %s %s", res, arg1, op, arg2);

        // If it successfully broke down into exactly 4 parts (like: x = y + 5)
        if (parts == 4) {
            
            // 1. Algebraic Simplification (e.g., x = y + 0)
            if ((strcmp(op, "+") == 0 && strcmp(arg2, "0") == 0) ||
                (strcmp(op, "-") == 0 && strcmp(arg2, "0") == 0) ||
                (strcmp(op, "*") == 0 && strcmp(arg2, "1") == 0) ||
                (strcmp(op, "/") == 0 && strcmp(arg2, "1") == 0)) {
                
                char new_inst[256];
                snprintf(new_inst, sizeof(new_inst), "%s = %s", res, arg1); // Simplify to just "Result = Arg1"
                
                printf("[Opt] Simplified: %s  ->  %s\n", inst, new_inst);
                free(curr->instr);
                curr->instr = strdup(new_inst);
                opt_count++;
            }
            
            // 2. Strength Reduction (e.g., x = y * 2)
            else if (strcmp(op, "*") == 0 && strcmp(arg2, "2") == 0) {
                char new_inst[256];
                snprintf(new_inst, sizeof(new_inst), "%s = %s + %s", res, arg1, arg1); // Change * 2 to +
                
                printf("[Opt] Strength Reduction: %s  ->  %s\n", inst, new_inst);
                free(curr->instr);
                curr->instr = strdup(new_inst);
                opt_count++;
            }
            
            // 3. Constant Folding (e.g., x = 5 + 3)
            else if (isdigit(arg1[0]) && isdigit(arg2[0])) {
                int val1 = atoi(arg1);
                int val2 = atoi(arg2);
                int final_val = 0;
                int can_fold = 1;
                
                // Do the math
                if (strcmp(op, "+") == 0) final_val = val1 + val2;
                else if (strcmp(op, "-") == 0) final_val = val1 - val2;
                else if (strcmp(op, "*") == 0) final_val = val1 * val2;
                else if (strcmp(op, "/") == 0) final_val = val1 / val2;
                else can_fold = 0; // Not a math operator

                if (can_fold == 1) {
                    char new_inst[256];
                    snprintf(new_inst, sizeof(new_inst), "%s = %d", res, final_val);
                    
                    printf("[Opt] Constant Folded: %s  ->  %s\n", inst, new_inst);
                    free(curr->instr);
                    curr->instr = strdup(new_inst);
                    opt_count++;
                }
            }
        }
        
        // If it only broke into 2 parts (like: x = x)
        else if (parts == 2) {
            
            // 4. Dead Code Elimination (Useless Assignment)
            if (strcmp(res, arg1) == 0) {
                 printf("[Opt] Removed Useless Assignment: %s\n", inst);
                 removed = 1;
                 opt_count++;
                 
                 // Remove the node from the linked list
                 if (prev != NULL) {
                     prev->next = curr->next;
                 }
            }
        }

        // Move to the next instruction
        if (removed == 0) {
            prev = curr;
        }
        curr = curr->next;
    }

    if (opt_count == 0) {
        printf("No optimizations could be applied.\n");
    } else {
        printf("Applied %d optimization(s) successfully.\n", opt_count);
    }
}

// ---------------------------------------------------------
// Target Code Generation Phase (Pseudo Assembly)
// ---------------------------------------------------------
void generate_target_code() {
    printf("\n=== Final Target Assembly Code ===\n");
    
    tac_instr *curr = get_tac_list();

    while (curr != NULL) {
        char inst[100];
        strcpy(inst, curr->instr);
        
        printf("\n; %s\n", inst);
        
        char result[50], arg1[50], op[10], arg2[50];
        char label_name[50], cond[50];

        // 1. Is it a Label? (e.g., L1:)
        if (strchr(inst, ':') != NULL) {
            printf("%s\n", inst);
        }
        
        // 2. Is it an IF statement? (e.g., if x goto L1)
        else if (sscanf(inst, "if %s goto %s", cond, label_name) == 2) {
            printf("LOAD R1, %s\n", cond);
            printf("CMP R1, 0\n");
            printf("JNE %s\n", label_name);
        }
        
        // 3. Is it a GOTO statement? (e.g., goto L1)
        else if (sscanf(inst, "goto %s", label_name) == 1) {
            printf("JMP %s\n", label_name);
        }
        
        // 4. Is it a RETURN statement?
        else if (sscanf(inst, "return %s", arg1) == 1) {
            printf("LOAD R1, %s\n", arg1);
            printf("RET R1\n");
        }
        
        // 5. Is it a Binary Operation? (e.g., x = y + z)
        else if (sscanf(inst, "%s = %s %s %s", result, arg1, op, arg2) == 4) {
            printf("LOAD R1, %s\n", arg1);
            printf("LOAD R2, %s\n", arg2);
            
            if (strcmp(op, "+") == 0)      printf("ADD R3, R1, R2\n");
            else if (strcmp(op, "-") == 0) printf("SUB R3, R1, R2\n");
            else if (strcmp(op, "*") == 0) printf("MUL R3, R1, R2\n");
            else if (strcmp(op, "/") == 0) printf("DIV R3, R1, R2\n");
            else                           printf("OP R3, R1, R2    // generic logic for '%s'\n", op);
            
            printf("STORE %s, R3\n", result);
        }
        
        // 6. Is it a Simple Assignment? (e.g., x = y)
        else if (sscanf(inst, "%s = %s", result, arg1) == 2) {
            if (arg1[0] == '-') { 
                printf("LOAD R1, %s\n", arg1 + 1); // skip negative sign
                printf("NEG R1\n");
                printf("STORE %s, R1\n", result);
            }
            else {
                printf("LOAD R1, %s\n", arg1);
                printf("STORE %s, R1\n", result);
            }
        }
        
        else {
            printf("; Unhandled Instruction Structure\n");
        }
        
        curr = curr->next;
    }
    printf("==================================\n\n");
}